Minor fixes

diff --git a/promoter b/promoter
--- a/promoter
+++ b/promoter
@@ -39,26 +39,26 @@ export PATH=$PATH:${BASE_DIR}/bin:${TARGET_BIN} ## add to path directory with lo
 get_argv_argument ()
 {
     argument=`echo $1 | sed 's/\-/\\\-/g'`
-    echo $ARGV | grep -oE "${argument}=[a-z,A-Z,0-9,/,:]*" | cut -d'=' -f2
+    echo $ARGV | grep -oE "${argument}=[a-z,A-Z,0-9,/,:]*" | cut -d'=' -f2 | tr '\n' '/'
 }
 
 export I_PREFIX=`get_argv_argument --prefix`
-[ -z ${I_PREFIX} ] && export I_PREFIX=/usr/local
+[ -z ${I_PREFIX} ] && export I_PREFIX=/usr/local/
 
 export I_BINDIR=`get_argv_argument --bindir`
-[ -Z ${I_BINDIR} ] && export I_BINDIR=$I_PREFIX/bin
+[ -Z ${I_BINDIR} ] && export I_BINDIR=${I_PREFIX}bin/
 
 export I_DATAROOTDIR=`get_argv_argument --sharedir`
-[ -z ${I_DATAROOTDIR} ] && export I_DATAROOTDIR=$I_PREFIX/share/jabs
+[ -z ${I_DATAROOTDIR} ] && export I_DATAROOTDIR=${I_PREFIX}share/jabs/
 
 export I_SRCDIR=`get_argv_argument --srcdir`
-[ -z ${I_SRCDIR} ] && export I_SRCDIR=$I_DATAROOTDIR/src
+[ -z ${I_SRCDIR} ] && export I_SRCDIR=${I_DATAROOTDIR}src/
 
 export I_LIBDIR=`get_argv_argument --libdir`
-[ -z ${I_LIBDIR} ] && export I_LIBDIR=$I_PREFIX/lib/jabs
+[ -z ${I_LIBDIR} ] && export I_LIBDIR=${I_PREFIX}lib/jabs/
 
 export I_SYSCONFIGDIR=`get_argv_argument --sysconfigdir`
-[ -z ${I_SYSCONFIGDIR} ] && export I_SYSCONFIGDIR=$I_PREFIX/etc/jabs
+[ -z ${I_SYSCONFIGDIR} ] && export I_SYSCONFIGDIR=${I_PREFIX}etc/jabs/
 
 ## /set variables
 
@@ -122,7 +122,6 @@ do_install()
 {
     ## Generate files with correct pathnames
     do_generate $I_BINDIR $I_SRCDIR $I_SYSCONFIGDIR $I_DATAROOTDIR $I_LIBDIR
-
     ## making destination direcotories
     mkdir -p $I_BINDIR $I_SRCDIR $I_SYSCONFIGDIR $I_DATAROOTDIR $I_LIBDIR
 
@@ -133,8 +132,6 @@ do_install()
         mkdir -p $dst
         cp $i $dst
     done
-    # binary
-    cp bin/* $I_BINDIR
     # sysconfig
     cp etc/* $I_SYSCONFIGDIR
     # shared files
@@ -163,6 +160,9 @@ do_install()
         mkdir -p $dst
         cp $i $dst
     done
+    # binary
+    do_build_wrappers
+    cp bin/* $I_BINDIR
 }
 
 do_clean()
@@ -208,11 +208,20 @@ do_generate() # $PWD/bin/ $PWD/src/ $PWD/etc/ $PWD/share/ $PWD/lib/
     # SRCDIR BINDIR SBCL_BIN DATADIR LIBDIR DATAROOTDIR SYSCONFDIR
 
     sed "s|@SRCDIR@|$srcdir|" src/wrappers/jn/jn.sh.input > $PWD/bin/jn.sh && chmod a+x $PWD/bin/jn.sh
-    sed "s|@BINDIR@|$bindir|" src/wrappers/jab/make-jab.lisp.input > src/wrappers/jab/make-jab.lisp
+    sed "s|@BINDIR@|$bindir|;s|@SRCDIR@|$srcdir|" src/wrappers/jab/make-jab.lisp.input > src/wrappers/jab/make-jab.lisp
     sed "s|@SRCDIR@|$srcdir|;s|@SBCL_BIN@|$SBCL_BIN|" src/wrappers/jab/jab.lisp.input > src/wrappers/jab/jab.lisp
     sed "s|@SRCDIR@|$srcdir|" src/jabs-loader.lisp.input > src/jabs-loader.lisp
     sed "s|@SRCDIR@|$srcdir|;s|@LIBDIR@|$libdir|;s|@DATAROOTDIR@|$datarootdir|;s|@SYSCONFIGDIR@|$sysconfigdir|;s|@JABS_VERSION@|$JABS_VERSION|" src/jabs-core.lisp.input > src/jabs-core.lisp
 
+    echo "${PURPLE}DONE${NO_COLOUR}"
+}
+
+do_build_wrappers ()
+{
+    echo -n "${PURPLE}Building${NO_COLOUR} wrappers... "
+    $SBCL --load ./src/wrappers/jab/make-jab.lisp >/dev/null
+    ret=$?
+    [ $ret != 0 ] && echo "${PURPLE}Build${NO_COLOUR} ${RED}FAILED${NO_COLOUR}">&2 && exit $ret
     echo "${PURPLE}DONE${NO_COLOUR}"
 }
 
@@ -261,12 +270,7 @@ do_build()
     echo "${PURPLE}DONE${NO_COLOUR}"
 
     do_generate $PWD/bin/ $PWD/src/ $PWD/etc/ $PWD/share/ $PWD/lib/
-
-    echo -n "${PURPLE}Building${NO_COLOUR} wrappers... "
-    $SBCL --load ./src/wrappers/jab/make-jab.lisp >/dev/null
-    ret=$?
-    [ $ret != 0 ] && echo "${PURPLE}Build${NO_COLOUR} ${RED}FAILED${NO_COLOUR}">&2 && exit $ret
-    echo "${PURPLE}DONE${NO_COLOUR}"
+    do_build_wrappers
     # echo
     # echo "You can operate now with ${CYAN}\`\`jab''${NO_COLOUR} utility from local directory, or do ${CYAN}\`\`./jab --self-install''${NO_COLOUR} to install it globally"
     # echo
@@ -406,10 +410,10 @@ case $1 in
         ;;
     "install")
         shift
-        # check_sbcl || do_sbcl
-        # ret=$?
-        # [ $ret != 0 ] && echo ">> ${RED}FAILED${NO_COLOUR} step">&2 && exit $ret
-        # print_step_done
+        check_sbcl || do_sbcl
+        ret=$?
+        [ $ret != 0 ] && echo ">> ${RED}FAILED${NO_COLOUR} step">&2 && exit $ret
+        print_step_done
 
         # print_step "${PURPLE}Building${NO_COLOUR} JABS"
         # do_build
